import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Noto_Sans, Nunito, Outfit } from "next/font/google"
import { NextAuthProvider } from "./SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Login from "@/components/Login";
import { FocusProvider } from "@/context/FocusContext";

const outfit = Outfit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--outfit",
  preload: true,
  subsets: ["latin"]
});

export const metadata = {
  title: "Chat GPT",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${outfit.variable} font-Outfit bg-primary text-foreground`}>
        <FocusProvider>
          <NextAuthProvider session={session}>
            {!session ? (
              <Login />
            ) : (
              <div className="flex">

                {/* Sidebar */}
                <div className="w-full h-screen max-w-xs">
                  <Sidebar />
                </div>

                {/* Provider */}

                {/* Content */}
                <div className="flex-1">
                  {/* <button className="absolute left-0 z-40 text-foreground top-1/2">
                    <ChevronLeft />
                  </button> */}
                  {children}
                </div>

              </div>
            )}
          </NextAuthProvider>
        </FocusProvider>
      </body>
    </html >
  );
}
